# Name of the workflow
name: Create Release
#Run on every commit tag with "v" (e.g. "v1.12.0")
on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
      - main
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
#Automatically create a GitHub release, with release details 
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: "hewa1303/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.CHANGELOG_RELEASE }}"
          prerelease: false
